# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "Cloudflare 2"
client_id = "125e8f870aa8ddea41f558c2b566f209"
application_url = "https://remix-cloudflare-workers.dan-gamble.workers.dev"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,write_checkout_branding_settings,write_files,write_pixels,read_customer_events,write_publications,write_cart_transforms"

[auth]
redirect_urls = [
  "https://remix-cloudflare-workers.dan-gamble.workers.dev/auth/callback",
  "https://remix-cloudflare-workers.dan-gamble.workers.dev/auth/shopify/callback",
  "https://remix-cloudflare-workers.dan-gamble.workers.dev/api/auth/callback",
  "https://remix-cloudflare-workers.dan-gamble.workers.dev/.shopify/graphiql/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false
